### ISSUE TITLE
imghdr removal

### ISSUE THREAD

**Issue by RomainBrault** [google/pybadges#47]
Deprecated since version 3.11, will be removed in version 3.13

See: https://docs.python.org/3/library/imghdr.html

**Comment by MattTheCuber** [comment]
Using pybadges on Python 3.13 no fails with the expected error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File ".../.venv/lib/python3.13/site-packages/pybadges/__init__.py", line 33, in <module>
    import imghdr
ModuleNotFoundError: No module named 'imghdr'
```
